FROM golang:1.17

ENV TZ America/Santiago

# Copy zoneinfo file and then remove cache
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime
RUN go install github.com/githubnemo/CompileDaemon@latest

EXPOSE 8080

ARG APPNAME
ARG MAIN_FILE
ENV APPNAME ${APPNAME:-trans}
ENV MAIN_FILE ${MAIN_FILE:-cmd/${APPNAME}/main.go}

WORKDIR /app

CMD CompileDaemon -log-prefix=false -build="go build -v -o ${APPNAME} ./${MAIN_FILE}" -command="./${APPNAME}"
