apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-trans-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "trans.labels" . | indent 4 }}
data:
  NEWRELIC_ENABLED: "{{ .Values.newrelic.enabled }}"
  TRANS_COMMANDS: "{{ .Values.trans.commands }}"
  TRANS_HOST: "{{ .Values.trans.host }}"
  TRANS_PORT: "{{ .Values.trans.port }}"
  TRANS_TIMEOUT: "{{ .Values.trans.timeout }}"
  PROMETHEUS_ENABLED: "{{ .Values.prometheus.enabled }}"
